apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ APP_NAME }}-config
  namespace: {{ NAMESPACE }}
data:
  APP_ENV: "production"
  APP_DEBUG: "false"
  DB_CONNECTION: "sqlite"
  DB_DATABASE: "/var/www/html/database/database.sqlite"
  CACHE_DRIVER: "file"
  SESSION_DRIVER: "file"
  QUEUE_CONNECTION: "sync"