apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ APP_NAME }}-app
  labels:
    app: {{ APP_NAME }}-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ APP_NAME }}-app
  template:
    metadata:
      labels:
        app: {{ APP_NAME }}-app
    spec:
      containers:
      - name: {{ APP_NAME }}-app
        image: {{ REGISTRY }}/{{ APP_NAME }}:latest
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: {{ APP_NAME }}-config
        env:
        - name: APP_URL
          value: "https://{{ DOMAIN }}"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5