<?php

namespace Algethamy\LaravelAckDeploy\Console\Commands;

use Illuminate\Console\Command;
use Symfony\Component\Process\Process;

class AckBuildCommand extends Command
{
    protected $signature = 'ack:build 
                           {--tag=latest : Docker image tag}
                           {--registry= : Docker registry URL}
                           {--push : Push image to registry after build}';

    protected $description = 'Build Docker image for ACK deployment';

    public function handle(): int
    {
        $this->info('🔨 Building Docker image for ACK deployment...');

        $config = $this->getConfiguration();

        // Build image
        if (!$this->buildImage($config)) {
            return self::FAILURE;
        }

        // Push if requested
        if ($this->option('push')) {
            if (!$this->pushImage($config)) {
                return self::FAILURE;
            }
        }

        $this->info('✅ Docker image build completed successfully!');
        $this->newLine();
        $this->info("Image: {$config['image']}");
        
        if (!$this->option('push')) {
            $this->info('To push the image, run: php artisan ack:build --push');
        }

        return self::SUCCESS;
    }

    private function getConfiguration(): array
    {
        $registry = $this->option('registry') ?: $this->getRegistryFromEnv();
        $appName = $this->getAppNameFromEnv();
        $tag = $this->option('tag');

        // Sanitize app name for Docker/Kubernetes compatibility
        $sanitizedAppName = $this->sanitizeDockerName($appName);

        // Format image name based on registry
        $imageName = $this->formatImageName($registry, $sanitizedAppName, $tag);

        return [
            'registry' => $registry,
            'app_name' => $sanitizedAppName,
            'tag' => $tag,
            'image' => $imageName,
        ];
    }

    private function buildImage(array $config): bool
    {
        if (!file_exists(base_path('Dockerfile.ack'))) {
            $this->error('Dockerfile.ack not found. Run: php artisan ack:init');
            return false;
        }

        $this->info("Building image: {$config['image']}");

        $process = new Process([
            'docker', 'build',
            '--platform', 'linux/amd64',
            '-t', $config['image'],
            '-f', 'Dockerfile.ack',
            '.'
        ], base_path());

        $process->setTimeout(600); // 10 minutes

        $process->run(function ($type, $buffer) {
            if (Process::ERR === $type) {
                $this->error($buffer);
            } else {
                $this->line($buffer);
            }
        });

        if (!$process->isSuccessful()) {
            $this->error('Docker build failed');
            return false;
        }

        $this->info('Docker image built successfully');
        return true;
    }

    private function pushImage(array $config): bool
    {
        $this->info("Pushing image: {$config['image']}");

        $process = new Process([
            'docker', 'push', $config['image']
        ]);

        $process->setTimeout(600); // 10 minutes

        $process->run(function ($type, $buffer) {
            if (Process::ERR === $type) {
                $this->error($buffer);
            } else {
                $this->line($buffer);
            }
        });

        if (!$process->isSuccessful()) {
            $this->error('Docker push failed');
            return false;
        }

        $this->info('Docker image pushed successfully');
        return true;
    }

    private function getRegistryFromEnv(): string
    {
        // First check .env.ack file (generated by ack:init)
        if (file_exists(base_path('.env.ack'))) {
            $envContent = file_get_contents(base_path('.env.ack'));
            if (preg_match('/^DOCKER_REGISTRY=(.+)$/m', $envContent, $matches)) {
                $registry = trim($matches[1]);
                // Remove quotes if present
                $registry = trim($registry, '"\'');
                if ($registry) {
                    return $registry;
                }
            }
        }
        
        // Fallback to main env
        $registry = env('DOCKER_REGISTRY');
        
        return $registry ?: 'registry.me-central-1.aliyuncs.com';
    }

    private function getAppNameFromEnv(): string
    {
        // First check .env.ack file (generated by ack:init)
        if (file_exists(base_path('.env.ack'))) {
            $envContent = file_get_contents(base_path('.env.ack'));
            if (preg_match('/^APP_NAME=(.+)$/m', $envContent, $matches)) {
                $appName = trim($matches[1]);
                // Remove quotes if present
                $appName = trim($appName, '"\'');
                if ($appName) {
                    return $appName;
                }
            }
        }
        
        // Fallback to main env
        $appName = env('APP_NAME');
        
        return $appName ?: basename(base_path());
    }

    private function formatImageName(string $registry, string $appName, string $tag): string
    {
        // Handle Docker Hub format
        if (in_array($registry, ['docker.io', 'hub.docker.com'])) {
            // For Docker Hub, if appName already contains username (like "algethamy/test_ack")
            // use it directly, otherwise add the username prefix
            if (str_contains($appName, '/')) {
                return "{$appName}:{$tag}"; // e.g., "algethamy/test_ack:latest"
            } else {
                // If no username in app name, assume it's just the repo name
                return "{$appName}:{$tag}"; // e.g., "test_ack:latest"
            }
        }

        // For other registries, use full format
        return "{$registry}/{$appName}:{$tag}";
    }

    private function sanitizeDockerName(string $name): string
    {
        // For Docker names, convert underscores to hyphens and ensure lowercase
        $sanitized = strtolower($name);
        $sanitized = str_replace('_', '-', $sanitized);

        // Remove any characters that aren't alphanumeric, hyphens, or slashes (for usernames)
        $sanitized = preg_replace('/[^a-z0-9-\/]/', '-', $sanitized);

        // Clean up consecutive hyphens
        $sanitized = preg_replace('/-+/', '-', $sanitized);

        // Remove leading/trailing hyphens (but preserve slashes for Docker Hub usernames)
        $sanitized = preg_replace('/^-+|-+$/', '', $sanitized);

        return $sanitized ?: 'laravel-app';
    }
}